name: Daily Commit Workflow

on:
  schedule:
    # This cron expression schedules the action to run once per day at midnight UTC
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC

jobs:
  commit:
    runs-on: ubuntu-latest  # The runner used for the job
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out your repository code

    - name: Add a daily commit by 22f3002902@ds.study.iitm.ac.in
      run: |
        # Create a simple text file to update daily
        echo "Daily commit to track activity" >> daily_activity.txt
        # Set up Git configuration
        git config user.name "GitHub Actions"
        git config user.email "22f3002902@ds.study.iitm.ac.in"
        # Stage and commit the changes
        git add daily_activity.txt
        git commit -m "Daily update - Automated commit"
        # Push the commit to the repository
        git push
